import{a as f,i as l,S as L}from"./assets/vendor-0Fq3u7cb.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&e(u)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function e(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const v=document.querySelector(".loader"),b="45157034-b6e4e263cfc131778ce7a37cc",w="https://pixabay.com/api/";async function h(s,r){const n=new URLSearchParams({key:b,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r});try{return(await f.get(`${w}?${n}`)).data}catch(e){l.error({maxWidth:"370px",position:"topRight",messageColor:"white",backgroundColor:"red",message:`${e}`}),v.classList.add("visually-hidden")}}const m=document.querySelector(".gallery");document.querySelector(".loader");function g(s){let r=s.hits.map(e=>`<li>
        <a class="gallery-link" href=${e.largeImageURL}>
          <img src="${e.webformatURL}" alt="${e.tags}" width=360 height=200>
          <div class="gallery-text">
            <p><span>Likes</span>${e.likes}</p>
            <p><span>Views</span>${e.views}</p>
            <p><span>Comments</span>${e.comments}</p>
            <p><span>Downloads</span>${e.downloads}</p>
          </div>
        </a>
      </li>`).join("");m.insertAdjacentHTML("beforeend",r),new L(".gallery a",{captionDelay:250,captionPosition:"bottom",captionsData:"alt"}).refresh()}function C(s){m.innerHTML="",l.error({maxWidth:"370px",position:"topRight",messageColor:"white",backgroundColor:"red",message:`${s}`})}const S=document.querySelector(".gallery"),y=document.querySelector(".form"),x=document.querySelector(".input"),a=document.querySelector(".loader"),d=document.querySelector(".btn");let c,i=1,q=15,p=0;y.addEventListener("submit",$);d.addEventListener("click",P);function $(s){if(s.preventDefault(),S.innerHTML="",d.classList.add("visually-hidden"),a.classList.remove("visually-hidden"),c=x.value.trim(),c===""){a.classList.add("visually-hidden"),l.error({maxWidth:"370px",position:"topRight",messageColor:"white",backgroundColor:"red",message:"This field can not be empty! Please, write your request!"});return}i=1,h(c,i).then(r=>{p=Math.ceil(r.totalHits/q),a.classList.add("visually-hidden"),r.hits.length===0?l.error({maxWidth:"370px",position:"topRight",messageColor:"white",backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!"}):(a.classList.add("visually-hidden"),g(r),i<p&&d.classList.remove("visually-hidden"))}).catch(C),y.reset()}async function P(s){i+=1,a.classList.remove("visually-hidden");const r=await h(c,i);g(r);const e=document.querySelector(".gallery li").getBoundingClientRect().height;if(window.scrollBy({top:e*2,behavior:"smooth"}),a.classList.add("visually-hidden"),i>=p)return d.classList.add("visually-hidden"),l.error({position:"topRight",messageColor:"black",backgroundColor:"blue",message:"We're sorry, but you've reached the end of search results."})}
//# sourceMappingURL=commonHelpers.js.map
