import{a as y,i as l,S as b}from"./assets/vendor-0Fq3u7cb.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&e(d)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function e(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const L="45157034-b6e4e263cfc131778ce7a37cc",v="https://pixabay.com/api/";async function h(s,r){const a=new URLSearchParams({key:L,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r});try{return(await y.get(`${v}?${a}`)).data}catch(e){l.error({maxWidth:"370px",position:"topRight",messageColor:"white",backgroundColor:"red",message:`${e}`})}}const m=document.querySelector(".gallery");function g(s){let r=s.hits.map(e=>`<li>
        <a class="gallery-link" href=${e.largeImageURL}>
          <img src="${e.webformatURL}" alt="${e.tags}" width=360 height=200>
          <div class="gallery-text">
            <p><span>Likes</span>${e.likes}</p>
            <p><span>Views</span>${e.views}</p>
            <p><span>Comments</span>${e.comments}</p>
            <p><span>Downloads</span>${e.downloads}</p>
          </div>
        </a>
      </li>`).join("");m.insertAdjacentHTML("beforeend",r),new b(".gallery a",{captionDelay:250,captionPosition:"bottom",captionsData:"alt"}).refresh()}function w(s){m.innerHTML="",l.error({maxWidth:"370px",position:"topRight",messageColor:"white",backgroundColor:"red",message:"Ooops, something went wrong!"})}const C=document.querySelector(".gallery"),f=document.querySelector(".form"),x=document.querySelector(".input"),n=document.querySelector(".loader"),p=document.querySelector(".btn");let c,i=1,S=15,u=0;f.addEventListener("submit",q);p.addEventListener("click",P);function q(s){if(s.preventDefault(),C.innerHTML="",n.classList.remove("visually-hidden"),c=x.value.trim(),c===""){n.classList.add("visually-hidden"),l.error({maxWidth:"370px",position:"topRight",messageColor:"white",backgroundColor:"red",message:"This field can not be empty! Please, write your request!"});return}i=1,h(c,i).then(r=>{u=Math.ceil(r.totalHits/S),n.classList.add("visually-hidden"),r.hits.length===0?l.error({maxWidth:"370px",position:"topRight",messageColor:"white",backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!"}):(n.classList.add("visually-hidden"),g(r),i<u&&p.classList.remove("visually-hidden"))}).catch(w),f.reset()}async function P(s){i+=1,n.classList.remove("visually-hidden");const r=await h(c,i);g(r);const e=document.querySelector(".gallery li").getBoundingClientRect().height;if(window.scrollBy({top:e*2,behavior:"smooth"}),i>=u)return p.classList.add("visually-hidden"),l.error({position:"topRight",messageColor:"black",backgroundColor:"blue",message:"We're sorry, but you've reached the end of search results."})}
//# sourceMappingURL=commonHelpers.js.map
